// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF97WuufWSOcql8paaGQc4ghMauVenQlo',
    appId: '1:576528444163:web:312b1bec00fa88fa661736',
    messagingSenderId: '576528444163',
    projectId: 'time-sphere-51836',
    authDomain: 'time-sphere-51836.firebaseapp.com',
    storageBucket: 'time-sphere-51836.firebasestorage.app',
    measurementId: 'G-ZTVHJHGWEL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqD-Zt0bHyeBMGJUqA-iRpABdCGF6dio0',
    appId: '1:576528444163:android:9eac988a6bcf3ed8661736',
    messagingSenderId: '576528444163',
    projectId: 'time-sphere-51836',
    storageBucket: 'time-sphere-51836.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqv3K69kVZW2s7dEKCQb9of1ktwO4ofK4',
    appId: '1:576528444163:ios:92bef380c453cd9c661736',
    messagingSenderId: '576528444163',
    projectId: 'time-sphere-51836',
    storageBucket: 'time-sphere-51836.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqv3K69kVZW2s7dEKCQb9of1ktwO4ofK4',
    appId: '1:576528444163:ios:92bef380c453cd9c661736',
    messagingSenderId: '576528444163',
    projectId: 'time-sphere-51836',
    storageBucket: 'time-sphere-51836.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF97WuufWSOcql8paaGQc4ghMauVenQlo',
    appId: '1:576528444163:web:8ad58711bd8d97f3661736',
    messagingSenderId: '576528444163',
    projectId: 'time-sphere-51836',
    authDomain: 'time-sphere-51836.firebaseapp.com',
    storageBucket: 'time-sphere-51836.firebasestorage.app',
    measurementId: 'G-D7JYK1YDEM',
  );
}